In [1]:
from user_generator import user_generator
import pandas as pd

In [2]:
check_user = user_generator(50)
columns = ["dni", "nombre", "apellido_1", "apellido_2", "sexo", "edad", "comunidad_autonoma", "provincia", "pension", "grado_discapacidad", "estado_civil", "año_inicio_IMSERSO", "viajes_totales_IMSERSO", "viajes_2_ultimos_años", "canceled_trips_n3", "top_trip_last_year", "mean_score"]
df_check_users = pd.DataFrame(check_user, columns=columns)

df_check_users

,dni,nombre,apellido_1,apellido_2,sexo,edad,comunidad_autonoma,provincia,pension,grado_discapacidad,estado_civil,año_inicio_IMSERSO,viajes_totales_IMSERSO,viajes_2_ultimos_años,canceled_trips_n3,top_trip_last_year,mean_score
0,22782411,FRANCISCO JAVIER,BENITEZ,CARNERERO,HOMBRE,81,ANDALUCIA,JAEN,2900.00,65,CASADX,2011,5,1,0,0,4.40
1,78192316,MUHAMMAD,GUILLEN,MUÑOZ,HOMBRE,70,CATALUÑA,TARRAGONA,1700.00,0,CASADX,2019,1,1,0,0,5.00
2,16631649,ALICIA,FERNANDEZ,HOZ,MUJER,76,CASTILLA-LA MANCHA,ALBACETE,1500.00,0,VIUDX,2015,4,0,0,0,2.75
3,88814496,MARIA JOSE,JUAN,FERNANDEZ,MUJER,81,CATALUÑA,BARCELONA,1300.00,33,CASADX,2022,0,0,0,0,-1.00
4,35017415,ANTONIA,DURAN,RAMOS,MUJER,72,COMUNIDAD DE MADRID,MADRID,950.00,0,VIUDX,2020,3,2,0,0,2.67
5,30944763,MERCEDES,FERNANDEZ,PEREZ,MUJER,90,CATALUÑA,BARCELONA,150.00,0,VIUDX,2020,1,0,0,0,5.00
6,40476002,ZENAIDA,VILLA,ALCAÑIZ,MUJER,71,CANARIAS,S. C. TENERIFE,2900.00,80,VIUDX,2021,1,1,0,0,5.00
7,81186335,ANA,LOPEZ,PEREZ,MUJER,67,CATALUÑA,GIRONA,3058.82,0,CASADX,2021,2,2,0,0,4.50
8,25459330,ANA,FERNANDEZ,TORO,MUJER,74,COMUNIDAD DE MADRID,MADRID,450.00,0,CASADX,2020,4,3,1,0,2.75
9,76333665,VANESA,BOTIA,ALVAREZ,MUJER,70,ILLES BALEARS,ILLES BALEARS,950.00,0,VIUDX,2019,1,0,0,0,5.00
10,58124370,MARIA TERESA,LUJAN,TOMILLO,MUJER,70,COMUNIDAD DE MADRID,MADRID,2200.00,0,SOLTERX,2020,4,2,0,0,4.25
11,60829764,INMACULADA,HURTADO,JIMENO,MUJER,81,PAIS VASCO,BIZKAIA,3000.00,33,CASADX,2019,5,3,0,0,3.60
12,93244506,MARIA,NITU,LIÑEIRO,MUJER,68,COMUNIDAD DE MADRID,MADRID,2700.00,0,VIUDX,2021,1,1,0,0,5.00
13,99859812,ADRIAN,ROBLES,DOMINGUEZ,HOMBRE,67,CASTILLA Y LEON,VALLADOLID,3058.82,0,CASADX,2021,3,3,1,0,4.00
14,92039996,JUAN JOSE,GARCIA,PIERNA,HOMBRE,66,ANDALUCIA,JAEN,2900.00,0,CASADX,2023,0,0,0,0,-1.00
15,53266738,MARIA ROSARIO,RAMIREZ,BLASCO,MUJER,71,COMUNIDAD DE MADRID,MADRID,750.00,0,VIUDX,2018,3,1,0,0,4.67
16,97913215,FATIMA ROSARIO,SERRANO,DEL PINO,MUJER,79,PRINCIPADO DE ASTURIAS,ASTURIAS,2200.00,0,SOLTERX,2019,3,2,0,1,2.67
17,45001922,FRANCISCO,DIAGNE,CANTOS,HOMBRE,73,ANDALUCIA,ALMERIA,1000.00,0,CASADX,2016,6,1,1,0,3.67
18,61635887,ERIC,EDROSA,FALERO,HOMBRE,77,PAIS VASCO,BIZKAIA,2700.00,0,VIUDX,2016,2,1,0,0,5.00
19,53626744,MISERICORDIA,CATALAN,AMIL,MUJER,73,ANDALUCIA,ALMERIA,2100.00,0,VIUDX,2021,1,1,0,0,4.00
20,52444874,MIGUEL,MIÑARRO,ZORRO,HOMBRE,76,CANARIAS,LAS PALMAS,450.00,0,CASADX,2020,3,3,0,0,3.67
21,60714079,YOLANDA,VIDAL,CALVIÑO,MUJER,68,COMUNIDAD VALENCIANA,VALENCIA,850.00,0,VIUDX,2022,0,0,0,0,-1.00
22,77549923,RAFAEL,GARCIA,CENDRERO,HOMBRE,72,COMUNIDAD DE MADRID,MADRID,1400.00,33,CASADX,2017,3,2,0,0,4.67
23,28238278,TOMAS,USAN,PEREZ,HOMBRE,73,GALICIA,PONTEVEDRA,1500.00,0,CASADX,2017,3,0,0,0,5.00
24,36756561,MARIA PALOMA,LUNA,COMA,MUJER,92,PAIS VASCO,GIPUZKOA,1500.00,0,VIUDX,2006,16,0,0,0,4.44
25,76047860,MARIO RODRIGO,MARTINEZ,HERNANDEZ,HOMBRE,68,ANDALUCIA,SEVILLA,800.00,0,CASADX,2021,2,2,0,0,5.00
26,48546455,PATRICIA,LUMERAS,ALARCON,MUJER,65,GALICIA,OURENSE,2300.00,0,CASADX,2023,0,0,0,0,-1.00
27,44351805,JOSE VICENTE,IRIARTE,CASTAÑEDA,HOMBRE,69,ANDALUCIA,MALAGA,1050.00,0,CASADX,2023,0,0,0,0,-1.00
28,14246072,ROSA MARIA,HERRERA,OVELLEIRO,MUJER,82,CANARIAS,S. C. TENERIFE,1400.00,80,SOLTERX,2021,1,1,0,0,5.00
29,25984163,OSCAR JOSE,FERNANDEZ,MOYA,HOMBRE,88,CANARIAS,LAS PALMAS,1600.00,0,CASADX,2011,9,2,0,1,4.67
30,60964867,JUDIT,PRATA,MARTINEZ,MUJER,75,COMUNIDAD VALENCIANA,VALENCIA,2800.00,0,CASADX,2021,0,0,0,0,-1.00
31,68465161,BERNARDO,RODRIGUEZ,MANCERA,HOMBRE,69,ANDALUCIA,SEVILLA,800.00,0,CASADX,2022,2,2,0,0,3.50
32,93743853,YOLANDA,SMITH,DE CASTRO,MUJER,80,ARAGON,ZARAGOZA,2200.00,0,VIUDX,2017,3,1,0,0,4.67
33,52820201,ALEXIS,LOPEZ,CERDA,HOMBRE,75,ANDALUCIA,CORDOBA,750.00,0,CASADX,2018,1,0,0,0,5.00
34,72795643,DOLORES,PEREZ,CUESTA,MUJER,71,ANDALUCIA,ALMERIA,1600.00,0,SOLTERX,2021,4,4,1,0,4.50
35,60094724,MARIA,CARDENAS,PEREZ,MUJER,75,CASTILLA-LA MANCHA,CUENCA,2200.00,33,CASADX,2017,4,1,0,0,5.00
36,12809434,TAMARA,LOPEZ,LOPEZ,MUJER,87,CANARIAS,S. C. TENERIFE,1000.00,0,CASADX,2011,10,3,3,0,4.50
37,31188194,OMAR,MORENO,GOMEZ,HOMBRE,68,CATALUÑA,BARCELONA,750.00,0,CASADX,2022,1,1,0,0,5.00
38,49455763,MERCEDES,GARCIA,RODRIGUEZ,MUJER,92,REGION DE MURCIA,MURCIA,3058.82,33,CASADX,2015,6,2,0,0,4.50
39,89294455,JOSE ANTONIO,RIVERO,FLORES,HOMBRE,74,CATALUÑA,BARCELONA,3058.79,0,CASADX,2021,0,0,0,0,-1.00
40,96800608,SUSANA,MAREQUE,RUIZ,MUJER,82,CATALUÑA,BARCELONA,2000.00,33,CASADX,2020,2,1,0,0,3.50
41,13707248,RICARDO ALBERTO,SANCHEZ,VILLALTA,HOMBRE,92,ARAGON,ZARAGOZA,750.00,0,VIUDX,2022,1,1,0,0,5.00
42,38283645,ANTONIO,YEPES,BARBANCHO,HOMBRE,77,CATALUÑA,BARCELONA,1000.00,0,CASADX,2014,11,3,3,1,4.09
43,50175251,PAULA,LOPEZ REY,FERNANDEZ,MUJER,97,CASTILLA-LA MANCHA,ALBACETE,2200.00,0,VIUDX,2001,16,3,0,0,4.50
44,98363975,CAYETANA,MARTINEZ,SALAZAR,MUJER,96,REGION DE MURCIA,MURCIA,1900.00,0,CASADX,2016,3,1,0,0,4.33
45,47646791,NURIA,SILGADO,AMADO,MUJER,71,ANDALUCIA,GRANADA,900.00,0,VIUDX,2018,3,2,0,1,5.00
46,41220849,JOSE SALVADOR,GOMEZ,MARTIN,HOMBRE,78,CATALUÑA,BARCELONA,1500.00,0,CASADX,2011,10,1,0,0,4.90
47,41661183,PATRICIO MANUEL,LOPEZ,PEREZ,HOMBRE,69,COMUNIDAD DE MADRID,MADRID,500.00,33,CASADX,2020,2,1,0,0,4.50
48,15866763,RAUL,CARDOZA,BRUNET,HOMBRE,74,GALICIA,A CORUÑA,900.00,0,CASADX,2016,3,1,0,0,2.33
49,94002075,SARA,LOPEZ,PARADA,MUJER,78,ANDALUCIA,CORDOBA,1700.00,0,CASADX,2014,7,2,0,0,4.29