In [3]:
from user_generator import user_generator
import pandas as pd

In [5]:
check_user = user_generator(25)
columns = ["dni", "nombre", "apellido_1", "apellido_2", "sexo", "edad", "comunidad_autonoma", "provincia", "pension", "grado_discapacidad", "estado_civil", "año_inicio_IMSERSO", "viajes_totales_IMSERSO", "viajes_2_ultimos_años"]
df_check_users = pd.DataFrame(check_user, columns=columns)

df_check_users

,dni,nombre,apellido_1,apellido_2,sexo,edad,comunidad_autonoma,provincia,pension,grado_discapacidad,estado_civil,año_inicio_IMSERSO,viajes_totales_IMSERSO,viajes_2_ultimos_años
0,85563468,RENE,TRINIDAD,VILLAVERDE,HOMBRE,65,COMUNIDAD DE MADRID,MADRID,1300.00,0,CASADX,2023,0,0
1,36008148,RUBEN,BARRIO,GARRIDO,HOMBRE,78,COMUNIDAD VALENCIANA,VALENCIA,750.00,33,CASADX,2017,1,1
2,25073105,ULISES,ACEBES,PALOMARES,HOMBRE,68,CASTILLA-LA MANCHA,GUADALAJARA,2000.00,0,CASADX,2022,1,1
3,16304428,MARIA CARMEN,JIMENEZ,LLORENS,MUJER,67,CANARIAS,LAS PALMAS,800.00,0,CASADX,2021,1,1
4,89483018,RAMON,UGARTE,RUIZ DE APODACA,HOMBRE,87,ILLES BALEARS,ILLES BALEARS,950.00,0,CASADX,2019,1,1
5,58353120,MARIA DORA,MARTINEZ,PARRA,MUJER,80,COMUNIDAD DE MADRID,MADRID,3058.82,0,CASADX,2020,3,1
6,54855410,SANDRA,SUAREZ,ALVAREZ,MUJER,95,PRINCIPADO DE ASTURIAS,ASTURIAS,1000.00,0,CASADX,2017,6,3
7,59482762,JESUS,FERNANDEZ,MUÑOZ,HOMBRE,78,COMUNIDAD VALENCIANA,VALENCIA,550.00,0,CASADX,2011,7,1
8,31884706,NOELIA,VALLES,RODRIGUEZ,MUJER,75,COMUNIDAD VALENCIANA,VALENCIA,3058.82,0,CASADX,2019,3,1
9,11109633,REBECA,YESTE,AYLLON,MUJER,76,PAIS VASCO,BIZKAIA,500.00,0,VIUDX,2018,6,2
10,61626926,JESUS,LOPEZ,GARCIA,HOMBRE,77,GALICIA,OURENSE,850.00,0,VIUDX,2019,1,1
11,53300551,NURIA,MORENA,PI,MUJER,84,ANDALUCIA,MALAGA,250.00,80,VIUDX,2007,8,2
12,55913896,ANTONIO,PENCHEV,SAGUER,HOMBRE,65,ANDALUCIA,ALMERIA,1400.00,33,CASADX,2023,0,0
13,85045384,ANAIS,OLIVA,GUIM,MUJER,94,CATALUÑA,BARCELONA,800.00,0,CASADX,2023,0,0
14,26271957,PAULA,REY,CASTAÑO,MUJER,67,CATALUÑA,BARCELONA,2300.00,65,SOLTERX,2022,0,0
15,49234742,JULIO,SERRANO,HARO,HOMBRE,80,GALICIA,PONTEVEDRA,1000.00,33,VIUDX,2011,8,1
16,17554516,JOSE LUIS,GALA,LASAOSA,HOMBRE,77,CATALUÑA,BARCELONA,550.00,0,CASADX,2019,5,2
17,45936733,BLANCA,ARROYO,SALCEDO,MUJER,86,COMUNIDAD VALENCIANA,VALENCIA,800.00,0,SOLTERX,2020,4,2
18,36845229,MARTA,MENDEZ,MIGUEL,MUJER,69,COMUNIDAD DE MADRID,MADRID,3058.82,0,CASADX,2020,0,0
19,46812705,BEATRIZ,SEGURA,PIÑEIRO,MUJER,88,COMUNIDAD VALENCIANA,ALICANTE,750.00,0,VIUDX,2010,6,0
20,35331875,MARIA NIEVES,ESTIARTE,AMIGO,MUJER,78,PAIS VASCO,BIZKAIA,2500.00,65,CASADX,2014,5,2
21,78783439,DAVID FRANCIS,GOÑI,PACHECO,HOMBRE,70,REGION DE MURCIA,MURCIA,3000.00,0,CASADX,2020,2,1
22,22586961,JOSE,BENAVENT,RINCON,HOMBRE,68,CATALUÑA,TARRAGONA,1600.00,0,CASADX,2020,4,3
23,85526922,CARME,SANTANA,ADRIA,MUJER,65,ANDALUCIA,SEVILLA,1600.00,0,VIUDX,2023,0,0
24,79362292,JOSEP M,HERRERO,ODRIOZOLA,HOMBRE,66,CASTILLA-LA MANCHA,TOLEDO,800.00,0,CASADX,2023,0,0